name = "OpenMeteo"
uuid = "18a3dba5-99ec-498b-9457-6d429bc375c9"
authors = ["TheCedarPrince <jacobszelko@gmail.com> and contributors"]
version = "0.0.1"

[deps]
FlatBuffers = "53afe959-3a16-52fa-a8da-cf864710bae9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
FlatBuffers = "0.6.2"
HTTP = "1.10.17"
URIs = "1.6.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
