# automatically generated by the FlatBuffers compiler, do not modify

FlatBuffers.@with_kw mutable struct VariablesWithTime{A}
    time::Int64 = 0
    time_end::Int64 = 0
    interval::Int32 = 0
    variables::Vector{A} = []
end
FlatBuffers.@ALIGN(VariablesWithTime, 1)
FlatBuffers.slot_offsets(::Type{T}) where {T<:VariablesWithTime} = [
    0x00000004, 0x00000006, 0x00000008, 0x0000000A
]

VariablesWithTime(buf::AbstractVector{UInt8}) = FlatBuffers.read(VariablesWithTime{VariableWithValues}, buf)
VariablesWithTime(io::IO) = FlatBuffers.deserialize(io, VariablesWithTime{VariableWithValues})

const ConcreteVariablesWithTime = VariablesWithTime{VariableWithValues}

read_ConcreteVariablesWithTime(buf::AbstractVector{UInt8}) = FlatBuffers.read(ConcreteVariablesWithTime, buf)
deserialize_ConcreteVariablesWithTime(io::IO) = FlatBuffers.deserialize(io, ConcreteVariablesWithTime)
